dist: focal

language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - gettext
      - appstream
      - libglib2.0-dev
      - libgtk-3-dev
      - libgcrypt20-dev
      - nettle-dev
      - libb2-dev
      - libmbedtls-dev
      - linux-libc-dev
      - librsvg2-bin
      - libxml2-utils
      - at-spi2-core
      - xvfb
      - gnome-icon-theme
      - libnautilus-extension-dev
      - libnemo-extension-dev
      - meson

script:
  - meson _build
      --buildtype=debug
      -Db_coverage=true
      -Dglib-checksums=true
      -Dlibcrypto=true
      -Dlinux-crypto=true
      -Dmbedtls=true
      -Dnettle=true
      -Dbuild-nautilus=true
      -Dbuild-nemo=true
  - xvfb-run -s "-screen 0 800x600x24" meson test -v -C _build

after_success:
  - bash <(curl -s https://codecov.io/bash)
