dist: focal

language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - meson
      - gcovr
      - gettext
      - appstream
      - libglib2.0-dev
      - libgtk-3-dev
      - libgcrypt20-dev
      - nettle-dev
      - libb2-dev
      - libmbedtls-dev
      - linux-libc-dev
      - librsvg2-bin
      - libxml2-utils
      - at-spi2-core
      - xvfb
      - gnome-icon-theme
      - libcaja-extension-dev
      - libnautilus-extension-dev
      - libnemo-extension-dev
      - libthunarx-3-dev

script:
  - meson _build
      --buildtype=debug
      -Db_coverage=true
      -Dglib-checksums=true
      -Dlibcrypto=true
      -Dlinux-crypto=true
      -Dmbedtls=true
      -Dnettle=true
      -Dbuild-caja=true
      -Dbuild-nautilus=true
      -Dbuild-nemo=true
      -Dbuild-thunar=true
  - cd _build
  - xvfb-run -s "-screen 0 800x600x24" meson test -v
  - test "${TRAVIS_COMPILER}" = "clang" || { ninja coverage && curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov && ./codecov -Z ; }
