dist: focal

language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libtool
      - gettext
      - autopoint
      - appstream
      - libglib2.0-dev
      - libgtk-3-dev
      - libgcrypt20-dev
      - nettle-dev
      - libb2-dev
      - libmbedtls-dev
      - linux-libc-dev
      - librsvg2-bin
      - libxml2-utils
      - at-spi2-core
      - xvfb
      - gnome-icon-theme
      - libnautilus-extension-dev
      - libnemo-extension-dev
      - meson

script:
  - meson _build
      --buildtype=debug
      -Db_coverage=true
      -Dlibcrypto=true
      -Dbuild-gtkhash=true
      -Dbuild-nemo=true
      -Dbuild-nautilus=true

  - cd _build
  - ninja
  - xvfb-run -s "-screen 0 800x600x24" meson test -v
  - xvfb-run -s "-screen 0 800x600x24" meson dist

after_success:
  - bash <(curl -s https://codecov.io/bash)
